name: migratio_app
description: Migratio – app (login + mapa + perfil) consumiendo vision-api
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  google_maps_flutter: ^2.14.0
  model_viewer_plus: ^1.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/migratio_logo.png
    - assets/pigeon_3.png
    - assets/globe.png
    - assets/earth.glb
    - assets/valparaiso.webp
    - assets/viña_del_mar.webp
    - assets/torres.jpg
    - assets/atacama.jpg
